// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA87ikQnvvf6tA7HvCsusGf9akQGqItynA',
    appId: '1:179342486434:web:0e5ee867eb536a553da0fb',
    messagingSenderId: '179342486434',
    projectId: 'edusage-mobile',
    authDomain: 'edusage-mobile.firebaseapp.com',
    storageBucket: 'edusage-mobile.firebasestorage.app',
    measurementId: 'G-1QGQ00JY6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX7HWB_xy8Fj0I-Qd0havGkcW-KhBCkug',
    appId: '1:179342486434:android:42d443bc2bb3ab3e3da0fb',
    messagingSenderId: '179342486434',
    projectId: 'edusage-mobile',
    storageBucket: 'edusage-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz6wexJ2QzRs6dB4SoPl0huG7gfvW_7hU',
    appId: '1:179342486434:ios:bf989405594687803da0fb',
    messagingSenderId: '179342486434',
    projectId: 'edusage-mobile',
    storageBucket: 'edusage-mobile.firebasestorage.app',
    iosBundleId: 'com.example.edusageMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz6wexJ2QzRs6dB4SoPl0huG7gfvW_7hU',
    appId: '1:179342486434:ios:bf989405594687803da0fb',
    messagingSenderId: '179342486434',
    projectId: 'edusage-mobile',
    storageBucket: 'edusage-mobile.firebasestorage.app',
    iosBundleId: 'com.example.edusageMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA87ikQnvvf6tA7HvCsusGf9akQGqItynA',
    appId: '1:179342486434:web:b07753e302dcc8113da0fb',
    messagingSenderId: '179342486434',
    projectId: 'edusage-mobile',
    authDomain: 'edusage-mobile.firebaseapp.com',
    storageBucket: 'edusage-mobile.firebasestorage.app',
    measurementId: 'G-PRXYYWN7VL',
  );
}
